const path=require("path")
const express=require("express")
const hbs=require("hbs")
const app=express()
const staticDir=path.join(__dirname,"../assets")
const viewsDir=path.join(__dirname,"../resourses/views")
const layautsDir=path.join(__dirname,"../resourses/layouts")
const customerRoutes= require("../routes/user.routes")
app.use(express.static(staticDir))
app.set("view engine","hbs")
app.set("views",viewsDir)
hbs.registerPartials(layautsDir)
app.use(express.urlencoded({extended:true}))
app.use(customerRoutes)
module.exports = app